using System.Linq;
using CrownAndColony.GameLogic.Specification;
using CrownAndColony.GameLogic.World;
using Xunit;

namespace CrownAndColony.GameLogic.Tests.World;

/// <summary>
/// Fixed scenario maps (<see cref="FixedMap"/>) — FreeCol's hand-made America map, loaded from the embedded
/// terrain grid extracted from <c>M_America_Mazim.fsm</c> (GPL v2). Terrain only; rivers/resources/natives/start
/// are layered on by the game-start generators (covered by the new-game tests).
/// </summary>
public class FixedMapTests
{
    private static readonly Ruleset Classic = Ruleset.LoadClassic();

    [Fact]
    public void America_LoadsTheFullAmericasGrid()
    {
        GameMap map = FixedMap.LoadAmerica(Classic);

        // FreeCol's M_America is a tall N–S strip of the Americas.
        Assert.Equal(40, map.Width);
        Assert.Equal(180, map.Height);

        // Every tile resolved to a real terrain type (the loader throws on an unknown id, so reaching here means
        // all 7200 tiles mapped); spot-check a couple of known cells from the source map's top-left corner.
        Assert.Equal("model.tile.mountains", map.TerrainAt(new Position(0, 0)).Id);
        Assert.Equal("model.tile.tundra", map.TerrainAt(new Position(2, 0)).Id);
    }

    [Fact]
    public void America_IsMostlyOcean_WithAMixOfNewWorldTerrain()
    {
        GameMap map = FixedMap.LoadAmerica(Classic);
        var counts = map.AllPositions()
            .GroupBy(p => map.TerrainAt(p).Id)
            .ToDictionary(g => g.Key, g => g.Count());

        // The Americas sit in a wide ocean: high-seas + ocean dominate (the FreeCol map is ~70% water).
        int water = map.AllPositions().Count(p => map.TerrainAt(p).IsWater);
        Assert.True(water > map.Width * map.Height / 2, $"expected mostly water, got {water}/{map.Width * map.Height}");

        // …and it carries varied New World land: mountains down the spine, tropical/boreal forest, prairie, tundra.
        foreach (string id in new[]
                 {
                     "model.tile.mountains", "model.tile.rainForest", "model.tile.borealForest",
                     "model.tile.prairie", "model.tile.tundra", "model.tile.plains",
                 })
        {
            Assert.True(counts.GetValueOrDefault(id, 0) > 0, $"expected some {id} on the America map");
        }
    }

    [Fact]
    public void America_IsDeterministic_SameBytesEveryLoad()
    {
        GameMap a = FixedMap.LoadAmerica(Classic);
        GameMap b = FixedMap.LoadAmerica(Classic);
        Assert.Equal(
            a.AllPositions().Select(p => a.TerrainAt(p).Id),
            b.AllPositions().Select(p => b.TerrainAt(p).Id));
    }

    [Fact]
    public void TryLoad_ReturnsTheFixedMap_ForAmerica_AndNull_ForRandom()
    {
        Assert.NotNull(FixedMap.TryLoad(MapSource.America, Classic));
        Assert.Null(FixedMap.TryLoad(MapSource.Random, Classic)); // Random is generated by the caller, not loaded
    }
}
